# ====================================================================================
# PLANTILLA MYSQL - PRODUCCIÓN
# ====================================================================================
# Configuración optimizada para ambientes de producción
# - Buffer pool grande (2GB - ajustar según RAM disponible)
# - 500 conexiones máximas
# - Optimizado para SSD
# - Logging selectivo
# - Seguridad reforzada
# 
# ⚠️ IMPORTANTE: Crear archivo .env en la raíz del proyecto mysql/ con:
#    MYSQL_ROOT_PASSWORD=tu_password_segura
#    MYSQL_USER=tu_usuario
#    MYSQL_PASSWORD=tu_password
#    MYSQL_DATABASE=tu_database
#    GF_ADMIN_USER=admin
#    GF_ADMIN_PASSWORD=tu_grafana_password
# ====================================================================================

services:
  # ==================================================================================
  # MYSQL DATABASE - PRODUCTION
  # ==================================================================================
  mysql:
    image: mysql:8.0
    container_name: mysql_prod
    restart: always
    
    env_file:
      - .env
    
    environment:
      # Variables cargadas desde .env
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      
      # Configuración de rendimiento (Producción - 8GB RAM)
      MYSQL_INNODB_BUFFER_POOL_SIZE: ${MYSQL_INNODB_BUFFER_POOL_SIZE:-2G}
      MYSQL_INNODB_BUFFER_POOL_INSTANCES: 8
      MYSQL_MAX_CONNECTIONS: ${MYSQL_MAX_CONNECTIONS:-500}
      MYSQL_INNODB_LOG_FILE_SIZE: 512M
      MYSQL_INNODB_LOG_BUFFER_SIZE: 64M
      MYSQL_INNODB_FLUSH_LOG_AT_TRX_COMMIT: 2
      
      # Optimizaciones para SSD
      MYSQL_INNODB_FLUSH_METHOD: O_DIRECT
      MYSQL_INNODB_IO_CAPACITY: 2000
      MYSQL_INNODB_IO_CAPACITY_MAX: 4000
      MYSQL_INNODB_READ_IO_THREADS: 8
      MYSQL_INNODB_WRITE_IO_THREADS: 8
      
      # Configuración de queries
      MYSQL_QUERY_CACHE_SIZE: 0
      MYSQL_QUERY_CACHE_TYPE: 0
      MYSQL_SORT_BUFFER_SIZE: 4M
      MYSQL_READ_BUFFER_SIZE: 2M
      MYSQL_READ_RND_BUFFER_SIZE: 4M
      MYSQL_JOIN_BUFFER_SIZE: 4M
      MYSQL_TMP_TABLE_SIZE: 64M
      MYSQL_MAX_HEAP_TABLE_SIZE: 64M
      
      # Thread pool
      MYSQL_THREAD_CACHE_SIZE: 100
      MYSQL_TABLE_OPEN_CACHE: 4000
      MYSQL_TABLE_DEFINITION_CACHE: 2000
      
      # Logging (solo errores y queries lentas)
      MYSQL_GENERAL_LOG: 0
      MYSQL_SLOW_QUERY_LOG: 1
      MYSQL_LONG_QUERY_TIME: 5
      MYSQL_LOG_ERROR_VERBOSITY: 2
      MYSQL_LOG_SLOW_ADMIN_STATEMENTS: 1
      MYSQL_LOG_SLOW_SLAVE_STATEMENTS: 1
    
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    
    volumes:
      - mysql_prod_data:/var/lib/mysql
      
      # Scripts de inicialización (crea usuario exporter)
      - ../init-scripts:/docker-entrypoint-initdb.d
      
      # Configuración personalizada (opcional)
      # - ../config/my.cnf:/etc/mysql/conf.d/custom.cnf:ro
    
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
      - --max-allowed-packet=256M
      - --skip-name-resolve
    
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Límites de recursos
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 8G
        reservations:
          cpus: '2.0'
          memory: 4G
    
    # Logging limitado
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    
    networks:
      - mysql_prod_network

  # ==================================================================================
  # MYSQLD EXPORTER - PRODUCTION
  # ==================================================================================
  mysqld-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysqld_exporter_prod
    restart: always
    
    environment:
      DATA_SOURCE_NAME: "exporter:exporter_password_123@(mysql:3306)/"
    
    ports:
      - "9104:9104"
    
    volumes:
      - ../.my.cnf:/.my.cnf:ro
    
    command:
      - --collect.info_schema.tables
      - --collect.info_schema.innodb_tablespaces
      - --collect.info_schema.innodb_metrics
      - --collect.global_status
      - --collect.global_variables
      - --collect.slave_status
      - --collect.info_schema.processlist
      - --collect.perf_schema.tablelocks
      - --collect.perf_schema.file_events
      - --collect.perf_schema.eventswaits
      - --collect.auto_increment.columns
      - --collect.binlog_size
      - --collect.perf_schema.tableiowaits
      - --collect.perf_schema.indexiowaits
    
    depends_on:
      mysql:
        condition: service_healthy
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    networks:
      - mysql_prod_network

  # ==================================================================================
  # PROMETHEUS - PRODUCTION
  # ==================================================================================
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_mysql_prod
    restart: always
    
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    
    volumes:
      - ../prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_mysql_prod_data:/prometheus
    
    depends_on:
      - mysqld-exporter
    
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
    
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"
    
    networks:
      - mysql_prod_network

  # ==================================================================================
  # GRAFANA - PRODUCTION
  # ==================================================================================
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_mysql_prod
    restart: always
    
    env_file:
      - .env
    
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_ADMIN_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: false
      GF_SERVER_ROOT_URL: ${GF_SERVER_ROOT_URL:-http://localhost:3000}
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
      GF_SECURITY_COOKIE_SECURE: true
      GF_SECURITY_STRICT_TRANSPORT_SECURITY: true
    
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    
    volumes:
      - ../grafana/provisioning:/etc/grafana/provisioning
      - grafana_mysql_prod_data:/var/lib/grafana
    
    depends_on:
      - prometheus
    
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    networks:
      - mysql_prod_network

# ====================================================================================
# VOLUMES
# ====================================================================================
volumes:
  mysql_prod_data:
    name: mysql_prod_data
  prometheus_mysql_prod_data:
    name: prometheus_mysql_prod_data
  grafana_mysql_prod_data:
    name: grafana_mysql_prod_data

# ====================================================================================
# NETWORKS
# ====================================================================================
networks:
  mysql_prod_network:
    name: mysql_prod_network
    driver: bridge
