# ====================================================================================
# PLANTILLA MYSQL - TESTING/CI-CD
# ====================================================================================
# Configuración mínima para pruebas automatizadas y CI/CD
# - Configuración muy ligera (64MB buffer pool)
# - Sin persistencia real (tmpfs para velocidad)
# - Logging mínimo
# - Ideal para pipelines de CI/CD
# ====================================================================================

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_test
    restart: "no"
    
    environment:
      MYSQL_ROOT_PASSWORD: test_root_pass
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
      MYSQL_DATABASE: test_database
      
      # Configuración mínima
      MYSQL_INNODB_BUFFER_POOL_SIZE: 64M
      MYSQL_MAX_CONNECTIONS: 20
      MYSQL_INNODB_LOG_FILE_SIZE: 24M
      MYSQL_INNODB_LOG_BUFFER_SIZE: 4M
      
      # Optimizaciones para velocidad (NO USAR EN PRODUCCIÓN)
      MYSQL_INNODB_FLUSH_LOG_AT_TRX_COMMIT: 0
      MYSQL_INNODB_DOUBLEWRITE: 0
      MYSQL_SYNC_BINLOG: 0
      
      MYSQL_QUERY_CACHE_SIZE: 0
      MYSQL_QUERY_CACHE_TYPE: 0
      MYSQL_SORT_BUFFER_SIZE: 1M
      
      # Sin logging
      MYSQL_GENERAL_LOG: 0
      MYSQL_SLOW_QUERY_LOG: 0
    
    ports:
      - "3306:3306"
    
    volumes:
      # Scripts de inicialización (crea usuario exporter)
      - ../init-scripts:/docker-entrypoint-initdb.d
    
    tmpfs:
      - /var/lib/mysql:rw,noexec,nosuid,size=512m
    
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
      - --skip-log-bin
    
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ptest_root_pass"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s
    
    networks:
      - mysql_test_network

  mysqld-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysqld_exporter_test
    restart: "no"
    
    environment:
      DATA_SOURCE_NAME: "exporter:exporter_password_123@(mysql:3306)/"
    
    ports:
      - "9104:9104"
    
    volumes:
      - ../.my.cnf:/.my.cnf:ro
    
    command:
      - --collect.global_status
      - --collect.info_schema.processlist
    
    depends_on:
      mysql:
        condition: service_healthy
    
    networks:
      - mysql_test_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_mysql_test
    restart: "no"
    
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=1d'
    
    ports:
      - "9090:9090"
    
    volumes:
      - ../prometheus.yml:/etc/prometheus/prometheus.yml:ro
    
    tmpfs:
      - /prometheus:rw,noexec,nosuid,size=256m,uid=65534,gid=65534
    
    depends_on:
      - mysqld-exporter
    
    networks:
      - mysql_test_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_mysql_test
    restart: "no"
    
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_USERS_ALLOW_SIGN_UP: false
    
    ports:
      - "3000:3000"
    
    volumes:
      - ../grafana/provisioning:/etc/grafana/provisioning
    
    tmpfs:
      - /var/lib/grafana
    
    depends_on:
      - prometheus
    
    networks:
      - mysql_test_network

networks:
  mysql_test_network:
    name: mysql_test_network
    driver: bridge
