# ====================================================================================
# PLANTILLA: ANALYTICS / DATA WAREHOUSE
# ====================================================================================
# Configuración optimizada para queries complejas y análisis de datos
# RAM recomendada: 2GB - 4GB
# Prioridad: Queries complejas, Lecturas masivas, Agregaciones
# ====================================================================================

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres_analytics
    hostname: postgres-analytics
    environment:
      # Credenciales
      POSTGRES_USER: analytics_user
      POSTGRES_PASSWORD: analytics_pass_456
      POSTGRES_DB: analytics_db
      
      # Configuración para análisis (optimizada para lecturas)
      POSTGRES_SHARED_BUFFERS: 1GB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 3GB
      POSTGRES_WORK_MEM: 128MB  # Alto para queries complejas
      POSTGRES_MAINTENANCE_WORK_MEM: 256MB
      POSTGRES_MAX_CONNECTIONS: 50
      
      # WAL y Checkpoints (menos crítico en analytics)
      POSTGRES_CHECKPOINT_TIMEOUT: 10min
      POSTGRES_MAX_WAL_SIZE: 2GB
      
      # Optimización para SSD y lecturas
      POSTGRES_RANDOM_PAGE_COST: 1.1
      POSTGRES_EFFECTIVE_IO_CONCURRENCY: 200
      POSTGRES_MAX_WORKER_PROCESSES: 8
      POSTGRES_MAX_PARALLEL_WORKERS_PER_GATHER: 4
      POSTGRES_MAX_PARALLEL_WORKERS: 8
      
      # Query Planner optimizado para analytics
      POSTGRES_DEFAULT_STATISTICS_TARGET: 500  # Muy alto
      POSTGRES_FROM_COLLAPSE_LIMIT: 16
      POSTGRES_JOIN_COLLAPSE_LIMIT: 16
      
      # Configuración para queries largas
      POSTGRES_STATEMENT_TIMEOUT: 0  # Sin timeout
      POSTGRES_IDLE_IN_TRANSACTION_SESSION_TIMEOUT: 30min
      
      # Autovacuum menos agresivo (analytics es principalmente read-only)
      POSTGRES_AUTOVACUUM_NAPTIME: 1min
      POSTGRES_AUTOVACUUM_MAX_WORKERS: 2
      
      # Logging de queries lentas
      POSTGRES_LOG_STATEMENT: none
      POSTGRES_LOG_MIN_DURATION_STATEMENT: 5000  # > 5 segundos
      POSTGRES_LOG_LINE_PREFIX: "%t [%p]: [%l-1] user=%u,db=%d"
      
      # Extensiones útiles para analytics
      # pg_stat_statements, pg_trgm, btree_gin, btree_gist
    
    ports:
      - "5435:5432"  # Analytics
    
    volumes:
      # Datos persistentes
      - postgres_analytics_data:/var/lib/postgresql/data
      
      # Scripts de inicialización automática
      - ../init-scripts/00-extensions.sql:/docker-entrypoint-initdb.d/00-extensions.sql:ro
      - ../init-scripts/01-monitoring-user.sql:/docker-entrypoint-initdb.d/01-monitoring-user.sql:ro
      # Scripts personalizados para analytics (opcional)
      # - ../init-scripts/01-init.sql.example:/docker-entrypoint-initdb.d/02-init.sql
    
    # Comando con configuraciones inline
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=3GB"
      - "-c"
      - "work_mem=128MB"
      - "-c"
      - "maintenance_work_mem=256MB"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "checkpoint_timeout=10min"
      - "-c"
      - "max_wal_size=2GB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "effective_io_concurrency=200"
      - "-c"
      - "max_worker_processes=8"
      - "-c"
      - "max_parallel_workers_per_gather=4"
      - "-c"
      - "max_parallel_workers=8"
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U analytics_user -d analytics_db"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s
    
    networks:
      - analytics_network
    
    restart: unless-stopped
    
    # Límites de recursos
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: "4G"
        reservations:
          cpus: "2.0"
          memory: "2G"
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres_exporter_analytics
    hostname: postgres-exporter-analytics
    environment:
      DATA_SOURCE_NAME: "postgresql://analytics_user:analytics_pass_456@postgres:5432/analytics_db?sslmode=disable"
      PG_EXPORTER_EXTEND_QUERY_PATH: "/etc/postgres-exporter/queries.yaml"
      PG_EXPORTER_DISABLE_DEFAULT_METRICS: "false"
      PG_EXPORTER_DISABLE_SETTINGS_METRICS: "false"
      
      # Métricas adicionales útiles para analytics
      PG_EXPORTER_INCLUDE_DATABASES: ".*"
      PG_EXPORTER_EXCLUDE_DATABASES: "template0,template1"
    
    ports:
      - "9190:9187"  # Analytics
    
    volumes:
      - ../config/queries/postgres-queries.yaml:/etc/postgres-exporter/queries.yaml:ro
    
    depends_on:
      postgres:
        condition: service_healthy
    
    networks:
      - analytics_network
    
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_analytics
    hostname: prometheus-analytics
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=30d"
      - "--storage.tsdb.retention.size=20GB"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
      - "--storage.tsdb.wal-compression"
    
    ports:
      - "9093:9090"  # Analytics
    
    volumes:
      - ../config/prometheus/analytics.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_analytics_data:/prometheus
    
    depends_on:
      - postgres-exporter
    
    networks:
      - analytics_network
    
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_analytics
    hostname: grafana-analytics
    environment:
      # Credenciales admin
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: analytics_admin_789
      
      # Configuración
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_USERS_ALLOW_ORG_CREATE: "false"
      GF_AUTH_ANONYMOUS_ENABLED: "false"
      
      # Paths
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
      GF_PATHS_DATA: /var/lib/grafana
      
      # Servidor
      GF_SERVER_HTTP_PORT: "3000"
      GF_SERVER_DOMAIN: localhost
      GF_SERVER_ROOT_URL: http://localhost:3003
      
      # Logging
      GF_LOG_LEVEL: info
      
      # Plugins útiles para analytics (opcional)
      # GF_INSTALL_PLUGINS: "grafana-piechart-panel,grafana-worldmap-panel"
    
    ports:
      - "3003:3000"
    
    volumes:
      - ../data/grafana/analytics:/var/lib/grafana
      - ../grafana/provisioning:/etc/grafana/provisioning:ro
    
    depends_on:
      - prometheus
    
    networks:
      - analytics_network
    
    restart: unless-stopped

volumes:
  postgres_analytics_data:
    driver: local
  prometheus_analytics_data:
    driver: local

networks:
  analytics_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.101.0/24
    name: analytics_network

# ====================================================================================
# CONFIGURACIÓN EXPLICADA
# ====================================================================================
# 
# CARACTERÍSTICAS:
# ✅ work_mem alto (128MB) para queries complejas con sorts/joins grandes
# ✅ Paralelización de queries habilitada (max_parallel_workers=8)
# ✅ Statistics target alto (500) para mejor optimización de queries
# ✅ Sin timeout de queries (útil para reportes largos)
# ✅ Optimizado para SSD con random_page_cost=1.1
# ✅ Autovacuum menos agresivo (principalmente read-only)
# ✅ Logging de queries > 5 segundos
# 
# IDEAL PARA:
# ✅ Data warehouses
# ✅ Reportes y BI
# ✅ Queries con JOINs complejos
# ✅ Agregaciones masivas
# ✅ Análisis de grandes volúmenes de datos
# ✅ ETL y data processing
# 
# NO RECOMENDADO PARA:
# ❌ OLTP con muchas escrituras
# ❌ Aplicaciones transaccionales
# ❌ APIs de alta concurrencia
# 
# USO:
# docker-compose -f templates/analytics.yml up -d
# 
# CON VARIABLES:
# docker-compose -f templates/analytics.yml --env-file .env up -d
# 
# EJEMPLO .env:
# POSTGRES_USER=analyst
# POSTGRES_PASSWORD=SecureAnalyticsPass123!
# POSTGRES_DB=datawarehouse
# POSTGRES_WORK_MEM=256MB  # Para queries muy grandes
# POSTGRES_MAX_CONNECTIONS=100
# 
# EXTENSIONES RECOMENDADAS:
# CREATE EXTENSION pg_stat_statements;  -- Análisis de queries
# CREATE EXTENSION pg_trgm;             -- Búsquedas de texto
# CREATE EXTENSION btree_gin;           -- Índices compuestos
# CREATE EXTENSION btree_gist;          -- Índices espaciales
# 
# ACCESO:
# - PostgreSQL: localhost:5432
# - Grafana: http://localhost:3000 (admin/analytics_admin_789)
# - Prometheus: http://localhost:9090
# - Exporter: http://localhost:9187/metrics
# 
# ====================================================================================
