services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres_conection_test
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test123 # Ojo con % en algunas apps
      POSTGRES_DB: test_db
      # Opcional: Configuración de performance
      # POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Para scripts SQL iniciales:
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    # Health check (opcional pero útil)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d test_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - monitoring
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://test:test123@postgres:5432/test_db?sslmode=disable"
      PG_EXPORTER_EXTEND_QUERY_PATH: "/etc/postgres-exporter/queries.yaml"
    ports:
      - "9187:9187"  # Puerto por defecto del exporter
    volumes:
      - ./postgres-queries.yaml:/etc/postgres-exporter/queries.yaml:ro
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - monitoring
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
      - '--storage.tsdb.retention.size=10GB'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    depends_on:
      - postgres-exporter
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      # Credenciales por defecto (cámbialas en producción)
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123
      # Permitir embedding en iframes (opcional)
      GF_SECURITY_ALLOW_EMBEDDING: "true"
      # Deshabilitar registro de usuarios
      GF_USERS_ALLOW_SIGN_UP: "false"
      # Auto-provisionar datasources y dashboards
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - monitoring
volumes:
  pgdata:
  prometheus_data:
  grafana_data:

networks:
  monitoring:
    driver: bridge