# ====================================================================================
# PLANTILLA: DESARROLLO (DEVELOPMENT)
# ====================================================================================
# Configuración ligera para desarrollo local y testing rápido
# RAM recomendada: 512MB - 1GB
# Prioridad: Velocidad de desarrollo > Performance
# ====================================================================================

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres_dev
    hostname: postgres-dev
    environment:
      # Credenciales básicas (cambiar en .env)
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_pass_123
      POSTGRES_DB: dev_database
      
      # Configuración de desarrollo (ligera)
      POSTGRES_SHARED_BUFFERS: 128MB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 512MB
      POSTGRES_WORK_MEM: 4MB
      POSTGRES_MAINTENANCE_WORK_MEM: 64MB
      POSTGRES_MAX_CONNECTIONS: 20
      POSTGRES_CHECKPOINT_TIMEOUT: 5min
      POSTGRES_MAX_WAL_SIZE: 512MB
      
      # Logging para desarrollo
      POSTGRES_LOG_STATEMENT: all
      POSTGRES_LOG_MIN_DURATION_STATEMENT: 100
      
    ports:
      - "5432:5432"  # Development
    
    volumes:
      # Datos persistentes
      - postgres_dev_data:/var/lib/postgresql/data
      
      # Scripts de inicialización automática
      - ../init-scripts/00-extensions.sql:/docker-entrypoint-initdb.d/00-extensions.sql:ro
      - ../init-scripts/01-monitoring-user.sql:/docker-entrypoint-initdb.d/01-monitoring-user.sql:ro
      # Scripts personalizados (opcional)
      # - ../init-scripts/01-init.sql.example:/docker-entrypoint-initdb.d/02-init.sql
    
    # Comando con configuraciones inline
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=128MB"
      - "-c"
      - "effective_cache_size=512MB"
      - "-c"
      - "work_mem=4MB"
      - "-c"
      - "maintenance_work_mem=64MB"
      - "-c"
      - "max_connections=20"
      - "-c"
      - "checkpoint_timeout=5min"
      - "-c"
      - "max_wal_size=512MB"
      - "-c"
      - "log_statement=all"
      - "-c"
      - "log_min_duration_statement=100"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "track_io_timing=on"
      - "-c"
      - "track_activities=on"
      - "-c"
      - "track_counts=on"
      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d dev_database"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    
    networks:
      dev_network:
        aliases:
          - postgres
          - postgres-dev
    
    restart: unless-stopped

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres_exporter_dev
    hostname: postgres-exporter-dev
    environment:
      DATA_SOURCE_NAME: "postgresql://dev_user:dev_pass_123@postgres:5432/dev_database?sslmode=disable"
      PG_EXPORTER_CONSTANTLABELS: "environment=development"
      PG_EXPORTER_EXTEND_QUERY_PATH: "/etc/postgres-exporter/queries.yaml"
      PG_EXPORTER_DISABLE_DEFAULT_METRICS: "false"
      PG_EXPORTER_DISABLE_SETTINGS_METRICS: "false"
    
    ports:
      - "9187:9187"
    
    volumes:
      - ../config/queries/postgres-queries.yaml:/etc/postgres-exporter/queries.yaml:ro
    
    depends_on:
      postgres:
        condition: service_healthy
    
    networks:
      dev_network:
        aliases:
          - postgres-exporter
          - postgres-exporter-dev
    
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_dev
    hostname: prometheus-dev
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=7d"
      - "--storage.tsdb.retention.size=5GB"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
      - "--web.enable-admin-api"
    
    ports:
      - "9090:9090"
    
    volumes:
      - ../config/prometheus/dev.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_dev_data:/prometheus
    
    depends_on:
      - postgres-exporter
    
    networks:
      dev_network:
        aliases:
          - prometheus
          - prometheus-dev
    
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_dev
    hostname: grafana-dev
    environment:
      # Credenciales admin
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: dev_admin_123
      
      # Configuración de desarrollo
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_USERS_ALLOW_ORG_CREATE: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "false"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Viewer"
      
      # Paths
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
      GF_PATHS_DATA: /var/lib/grafana
      
      # Servidor
      GF_SERVER_HTTP_PORT: "3000"
      GF_SERVER_DOMAIN: localhost
      GF_SERVER_ROOT_URL: http://localhost:3000
      
      # Logging
      GF_LOG_LEVEL: debug
    
    ports:
      - "3000:3000"
    
    volumes:
      - grafana_development_data:/var/lib/grafana
      - ../grafana/provisioning:/etc/grafana/provisioning:ro
    
    depends_on:
      - prometheus
    
    networks:
      dev_network:
        aliases:
          - grafana
          - grafana-dev
    
    restart: unless-stopped

volumes:
  postgres_dev_data:
    driver: local
  prometheus_dev_data:
    driver: local
  grafana_development_data:
    driver: local

networks:
  dev_network:
    driver: bridge
    name: dev_network

# ====================================================================================
# CONFIGURACIÓN EXPLICADA
# ====================================================================================
# 
# CARACTERÍSTICAS:
# ✅ Configuración ligera (128MB shared_buffers)
# ✅ Logging completo para debugging
# ✅ 20 conexiones máximas
# ✅ Reinicio automático en caso de fallo
# ✅ Health checks activos
# ✅ Retención de datos de 7 días en Prometheus
# ✅ Acceso anónimo habilitado en Grafana (solo desarrollo)
# 
# USO:
# docker-compose -f templates/development.yml up -d
# 
# CON VARIABLES:
# docker-compose -f templates/development.yml --env-file .env up -d
# 
# ACCESO:
# - PostgreSQL: localhost:5432
# - Grafana: http://localhost:3000 (admin/dev_admin_123)
# - Prometheus: http://localhost:9090
# - Exporter: http://localhost:9187/metrics
# 
# ====================================================================================
