# ====================================================================================
# PLANTILLA: TESTING (CI/CD)
# ====================================================================================
# Configuración mínima para tests automatizados y CI/CD
# RAM recomendada: 256MB - 512MB
# Prioridad: Velocidad de inicio > Persistencia
# ====================================================================================

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres_test
    hostname: postgres-test
    environment:
      # Credenciales de testing (NO usar en producción)
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_DB: test_db
      
      # Configuración mínima para testing
      POSTGRES_SHARED_BUFFERS: 64MB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 256MB
      POSTGRES_WORK_MEM: 2MB
      POSTGRES_MAINTENANCE_WORK_MEM: 32MB
      POSTGRES_MAX_CONNECTIONS: 10
      
      # Optimización para velocidad (NO SEGURO PARA PRODUCCIÓN)
      POSTGRES_FSYNC: off  # ⚠️ Desactiva sincronización de disco
      POSTGRES_SYNCHRONOUS_COMMIT: off
      POSTGRES_FULL_PAGE_WRITES: off
      
      # WAL mínimo
      POSTGRES_MAX_WAL_SIZE: 256MB
      POSTGRES_CHECKPOINT_TIMEOUT: 3min
      
      # Sin logging (performance)
      POSTGRES_LOG_STATEMENT: none
      POSTGRES_LOG_MIN_DURATION_STATEMENT: -1
    
    ports:
      - "5433:5432"  # Testing
    
    volumes:
      # Scripts de inicialización automática
      - ../init-scripts/00-extensions.sql:/docker-entrypoint-initdb.d/00-extensions.sql:ro
    
    # ⚠️ SIN VOLÚMENES PERSISTENTES - Los datos se pierden al eliminar el contenedor
    tmpfs:
      - /var/lib/postgresql/data  # Todo en memoria temporal
    
    # Comando con configuraciones inline para testing
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=64MB"
      - "-c"
      - "effective_cache_size=256MB"
      - "-c"
      - "work_mem=2MB"
      - "-c"
      - "maintenance_work_mem=32MB"
      - "-c"
      - "max_connections=10"
      - "-c"
      - "fsync=off"
      - "-c"
      - "synchronous_commit=off"
      - "-c"
      - "full_page_writes=off"
      - "-c"
      - "max_wal_size=256MB"
      - "-c"
      - "checkpoint_timeout=3min"
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
    
    networks:
      test_network:
        aliases:
          - postgres
    
    restart: "no"  # No reiniciar automáticamente en testing

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres_exporter_test
    hostname: postgres-exporter-test
    environment:
      DATA_SOURCE_NAME: "postgresql://test_user:test_pass@postgres:5432/test_db?sslmode=disable"
      PG_EXPORTER_EXTEND_QUERY_PATH: "/etc/postgres-exporter/queries.yaml"
      PG_EXPORTER_DISABLE_DEFAULT_METRICS: "false"
      PG_EXPORTER_DISABLE_SETTINGS_METRICS: "false"
    
    ports:
      - "9188:9187"  # Testing
    
    volumes:
      - ../config/queries/postgres-queries.yaml:/etc/postgres-exporter/queries.yaml:ro
    
    depends_on:
      postgres:
        condition: service_healthy
    
    networks:
      test_network:
        aliases:
          - postgres-exporter
    
    restart: "no"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_test
    hostname: prometheus-test
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=1d"
      - "--storage.tsdb.retention.size=1GB"
      - "--web.enable-lifecycle"
    
    ports:
      - "9091:9090"  # Testing
    
    user: "0:0"  # Corre como root para evitar problemas de permisos en tmpfs
    
    volumes:
      - ../config/prometheus/test.yml:/etc/prometheus/prometheus.yml:ro
    
    # Sin volumen persistente
    tmpfs:
      - /prometheus
    
    depends_on:
      - postgres-exporter
    
    networks:
      test_network:
        aliases:
          - prometheus
    
    restart: "no"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_test
    hostname: grafana-test
    environment:
      # Credenciales simples para testing
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      
      # Sin restricciones para testing
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_AUTH_ANONYMOUS_ENABLED: "false"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_BASIC_ENABLED: "true"
      
      # Paths
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
      
      # Logging mínimo
      GF_LOG_LEVEL: warn
    
    ports:
      - "3001:3000"
    
    volumes:
      - ../grafana/provisioning:/etc/grafana/provisioning:ro
    
    # Sin volumen persistente
    tmpfs:
      - /var/lib/grafana
    
    depends_on:
      - prometheus
    
    networks:
      - test_network
    
    restart: "no"

networks:
  test_network:
    driver: bridge
    name: test_network


# ====================================================================================
# CONFIGURACIÓN EXPLICADA
# ====================================================================================
# 
# CARACTERÍSTICAS:
# ✅ Configuración mínima (64MB shared_buffers)
# ✅ Inicio ultra-rápido (< 5 segundos)
# ✅ 10 conexiones máximas
# ✅ FSYNC desactivado (velocidad > seguridad)
# ✅ Sin volúmenes persistentes (todo en tmpfs/memoria)
# ✅ Sin reinicio automático
# ✅ Ideal para CI/CD pipelines
# 
# ⚠️ ADVERTENCIAS:
# ❌ NO usar en producción
# ❌ Los datos se pierden al eliminar contenedores
# ❌ FSYNC=off puede causar corrupción de datos
# ❌ Sin backups automáticos
# 
# USO EN CI/CD (GitHub Actions):
# ```yaml
# - name: Start PostgreSQL
#   run: docker-compose -f templates/testing.yml up -d
# 
# - name: Wait for PostgreSQL
#   run: docker-compose -f templates/testing.yml exec -T postgres pg_isready
# 
# - name: Run tests
#   run: npm test
# 
# - name: Cleanup
#   run: docker-compose -f templates/testing.yml down -v
# ```
# 
# USO LOCAL:
# docker-compose -f templates/testing.yml up -d
# # Ejecutar tests
# docker-compose -f templates/testing.yml down -v  # Limpiar todo
# 
# ACCESO:
# - PostgreSQL: localhost:5432 (test_user/test_pass)
# - Grafana: http://localhost:3000 (acceso anónimo)
# - Prometheus: http://localhost:9090
# 
# ====================================================================================
